apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nginx
  # these are replicas set labels
  labels: 
    purpose: helm-demo 
    project: roboshop 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: helm-demo
      project: roboshop 
  # pod defination
  template:
    metadata:
      labels:
        purpose: helm-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
